graph TD
    API --> MONGO
    API --> Auth
    API --> LinesServer
    LinesServer --> MONGO
    Filas --> LinesServer
    CertificateValidator --> MONGO
    subgraph AWS
        subgraph ElasticBeanstalk
            API
            LinesServer
            CertificateValidator
        end
    end
    
    subgraph MongoAtlas
     MONGO[(MONGODB)]
    end

    subgraph Auth0
     Auth[(Logins)]
    end

    subgraph Totens
     Filas
    end